<Project Sdk="Aspire.AppHost.Sdk/13.6.1">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>a9fbe979-c59c-4500-921f-8c902036bbce</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.6.1" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.6.1" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="13.6.1" />
    <PackageReference Include="Aspire.Hosting.Redis" Version="13.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Casino.Api\Casino.Api.csproj" />
    <ProjectReference Include="..\Casino.WalletService\Casino.WalletService.csproj" />
  </ItemGroup>

</Project>
