<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Casino.ServiceDefaults\Casino.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Modules\Wallet\Casino.Modules.Wallet.csproj" />
    <ProjectReference Include="..\Modules\Games\Casino.Modules.Games.csproj" />
    <ProjectReference Include="..\Modules\Realtime\Casino.Modules.Realtime.csproj" />
    <ProjectReference Include="..\Modules\Users\Casino.Modules.Users.csproj" />
    <ProjectReference Include="..\Modules\Promotions\Casino.Modules.Promotions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
