<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\Casino.ServiceDefaults\Casino.ServiceDefaults.csproj" />
    <ProjectReference Include="..\Casino.Hosting\Casino.Hosting.csproj" />
    <ProjectReference Include="..\Modules\Games\Casino.Modules.Games.csproj" />
    <ProjectReference Include="..\Modules\Realtime\Casino.Modules.Realtime.csproj" />
    <ProjectReference Include="..\Modules\Users\Casino.Modules.Users.csproj" />
    <ProjectReference Include="..\Modules\Promotions\Casino.Modules.Promotions.csproj" />
    <ProjectReference Include="..\Casino.Contracts\Casino.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.SignalR.StackExchangeRedis" Version="10.0.12" />
    <PackageReference Include="Microsoft.Extensions.ServiceDiscovery.Yarp" Version="10.10.0" />
    <PackageReference Include="Yarp.ReverseProxy" Version="2.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>228fb9ba-9caa-4cb8-bfcd-69d408976794</UserSecretsId>
  </PropertyGroup>

</Project>
