<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Marten" Version="9.47.0" />
    <PackageReference Include="WolverineFx.Marten" Version="6.48.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Casino.Contracts\Casino.Contracts.csproj" />
    <ProjectReference Include="..\..\Casino.BuildingBlocks\Casino.BuildingBlocks.csproj" />
  </ItemGroup>

</Project>
